create extension if not exists pg_trgm;
create table if not exists entities (
 id bigint generated by default as identity primary key,
 slug text unique not null,
 name_en text not null,
 name_ko text,
 name_hanja text,
 entity_type text not null,
 start_year int,
 end_year int,
 summary text,
 created_at timestamptz default now()
);
create table if not exists sources (
 id bigint generated by default as identity primary key,
 title text not null,
 institution text,
 source_type text,
 canonical_url text,
 citation text,
 rights_note text,
 created_at timestamptz default now()
);
create table if not exists relationships (
 id bigint generated by default as identity primary key,
 subject_id bigint references entities(id) on delete cascade,
 predicate text not null,
 object_id bigint references entities(id) on delete cascade,
 start_year int,
 end_year int,
 source_id bigint references sources(id),
 confidence numeric check (confidence between 0 and 1)
);
create index if not exists entities_name_en_trgm on entities using gin(name_en gin_trgm_ops);
create index if not exists entities_name_ko_trgm on entities using gin(name_ko gin_trgm_ops);
alter table entities enable row level security;
alter table sources enable row level security;
alter table relationships enable row level security;
create policy "public read entities" on entities for select using (true);
create policy "public read sources" on sources for select using (true);
create policy "public read relationships" on relationships for select using (true);
